spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs

# Desarrollo - Permitir HTTP
server.port=8080
server.ssl.enabled=false
server.ssl.key-store=
server.servlet.context-path=/
server.http2.enabled=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation1234567890
jwt.expiration=86400000
